apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: che-tls
  namespace: eclipse-che
spec:
  secretName: che-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: che.devpath.xyz
  dnsNames:
  - "che.devpath.xyz"
  - "*.che.devpath.xyz"
