apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-pv
  labels:
    environment: keyy
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/postgresql

