apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-pvc
  # namespace: key
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  selector:
    matchLabels:
      environment: keyy
